"""Django settings for appy-reviews project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/

"""
import os

import dj_database_url
import requests
from django.utils.log import DEFAULT_LOGGING


def bool_environ(key, default=''):
    value = os.getenv(key, default).lower()
    if value in ('', 'n', 'no', 'f', 'false', '0'):
        return False
    if value in ('y', 'yes', 't', 'true', '1'):
        return True
    raise ValueError(key)


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2n3(z!1*qc(&*-7((1$myom)7oyn@pr!348s&unjxr7-9-npm('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool_environ('APPY_DEBUG')

if DEBUG:
    EC2_PRIVATE_IP = None
else:
    ALLOWED_HOSTS = [
        'pro-reviews-dssg.us-west-2.elasticbeanstalk.com',
        'dev-reviews-dssg.us-west-2.elasticbeanstalk.com',
        'review.dssg.io',
    ]

    try:
        response = requests.get(
            'http://169.254.169.254/latest/meta-data/local-ipv4',
            timeout=0.01
        )
    except requests.exceptions.RequestException:
        EC2_PRIVATE_IP = None
    else:
        EC2_PRIVATE_IP = response.text

    if EC2_PRIVATE_IP:
        ALLOWED_HOSTS.append(EC2_PRIVATE_IP)


# Application definition

INSTALLED_APPS = [
    #
    # Django "contrib"
    #
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    #
    # 3rd-party
    #
    # allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # allauth enabled providers
    # 'allauth.socialaccount.providers.amazon',
    # 'allauth.socialaccount.providers.bitbucket',
    # 'allauth.socialaccount.providers.bitbucket_oauth2',
    # 'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',
    # 'allauth.socialaccount.providers.gitlab',
    'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.linkedin',
    # 'allauth.socialaccount.providers.linkedin_oauth2',
    # 'allauth.socialaccount.providers.openid',
    # 'allauth.socialaccount.providers.reddit',
    # 'allauth.socialaccount.providers.slack',
    # 'allauth.socialaccount.providers.stackexchange',
    # 'allauth.socialaccount.providers.trello',
    # 'allauth.socialaccount.providers.twitter',

    #
    # our apps
    #
    'review',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

SITE_ID = 1

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASE_SCHEMA = 'appy_reviews'
DATABASE_URL = os.getenv('DATABASE_URL')

DATABASES = {
    # Reads from environment variable DATABASE_URL
    # E.g., for production:
    #   postgres://appy_reviews:PASSWORD@postgres.dssg.io/appy_reviews
    'default': dict(
        dj_database_url.config(),
        OPTIONS={
            'options': f'-c search_path={DATABASE_SCHEMA}',
        },
    ),
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'review.Reviewer'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# allauth

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # TODO: test
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False

# review

REVIEW_PROGRAM_YEAR = 2018
REVIEW_SURVEY_LENGTH = 2

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'


# Logging

if not DEBUG:
    LOGGING = DEFAULT_LOGGING.copy()
    LOGGING['handlers']['console']['filters'] = ['require_debug_false']
    LOGGING['loggers']['django.server']['propagate'] = True
