# Generated by Django 2.0 on 2017-12-27 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('reviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'A reviewer with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('trusted', models.BooleanField(default=False, help_text='Designates that this reviewer can accept or reject applicant without submitting review.', verbose_name='trusted status')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('background', models.CharField(blank=True, choices=[('soc-sci', 'Social Science'), ('comp-sci', 'Computer Science'), ('math-stat', 'Math/Statistics')], max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this reviewer belongs to. A reviewer will get all permissions granted to each of their groups.', related_name='reviewers', related_query_name='reviewer', to='auth.Group')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this reviewer.', related_name='reviewers', related_query_name='reviewer', to='auth.Permission')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this reviewer should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reviewer',
            },
            managers=[
                ('objects', review.models.ReviewerManager()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'An applicant with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('lookup_path', models.CharField(max_length=300)),
                ('survey_id', models.IntegerField()),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=6)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Applicant')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('lookup_path', models.CharField(max_length=300)),
                ('survey_id', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Application')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Application')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.TextField()),
                ('submitted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('application', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('lookup_path', 'survey_id')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('lookup_path', 'survey_id')},
        ),
    ]
