# Generated by Django 2.0 on 2017-12-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPage',
            fields=[
                ('application_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=300)),
                ('column_name', models.CharField(max_length=300)),
                ('entity_code', models.CharField(max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Application')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application_page',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='applicationpage',
            unique_together={('table_name', 'column_name', 'entity_code')},
        ),

        migrations.AddField(
            model_name='application',
            name='program_year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='application',
            name='lookup_path',
        ),
        migrations.RemoveField(
            model_name='application',
            name='survey_id',
        ),

        migrations.AddField(
            model_name='reference',
            name='table_name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='column_name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='entity_code',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('table_name', 'column_name', 'entity_code')},
        ),
        migrations.RemoveField(
            model_name='reference',
            name='lookup_path',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='survey_id',
        ),
    ]
