# Generated by Django 2.0 on 2018-01-19 00:56

from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20171228_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', review.models.EnumCharField([('programming', 'Programming Ability'), ('machine_learning', 'Stats/Machine Learning Ability'), ('data_handling', 'Data Handling/Manipulation Skills'), ('interest_in_good', 'Interest in Social Good'), ('communication', 'Communication Ability'), ('teamwork', 'Would this person work well in a team?'), ('overall', 'Overall Recommendation')])),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'review_rating',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='interview_suggestions',
            field=models.TextField(blank=True, help_text="In an interview with this candidate, what should we focus on? Any red flags? Anything you would ask them about that's hard to judge from the application and references?"),
        ),
        migrations.AddField(
            model_name='review',
            name='would_interview',
            field=models.BooleanField(default=None, help_text='Would you like to interview this applicant?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='review.Applicant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(blank=True, help_text='Any comments on your recommendation?'),
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('review', 'label')},
        ),
    ]
