# Generated by Django 2.0 on 2018-01-31 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20180119_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationpage',
            options={'ordering': ('table_name', 'column_name', 'entity_code')},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('table_name', 'column_name', 'entity_code')},
        ),

        migrations.AddField(
            model_name='review',
            name='programming_rating',
            field=models.IntegerField(null=True, verbose_name='Programming Ability'),
        ),
        migrations.AddField(
            model_name='review',
            name='machine_learning_rating',
            field=models.IntegerField(null=True, verbose_name='Stats/Machine Learning Ability'),
        ),
        migrations.AddField(
            model_name='review',
            name='data_handling_rating',
            field=models.IntegerField(null=True, verbose_name='Data Handling/Manipulation Skills'),
        ),
        migrations.AddField(
            model_name='review',
            name='interest_in_good_rating',
            field=models.IntegerField(null=True, verbose_name='Interest in Social Good'),
        ),
        migrations.AddField(
            model_name='review',
            name='communication_rating',
            field=models.IntegerField(null=True, verbose_name='Communication Ability'),
        ),
        migrations.AddField(
            model_name='review',
            name='teamwork_rating',
            field=models.IntegerField(null=True, verbose_name='Would this person work well in a team?'),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_recommendation',
            field=review.models.EnumCharField([('accept', 'Accept'), ('reject', 'Reject'), ('only_if', 'Only if you need a certain type of fellow (explain below)')], help_text='Overall recommendation', null=True),
        ),

        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='review.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
