# Generated by Django 2.0 on 2018-02-01 18:35

from django.db import migrations
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20180131_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='overall_recommendation',
            field=review.models.EnumCharField([('interview', 'Interview'), ('reject', 'Reject'), ('only_if', 'Only if you need a certain type of fellow (explain below)')], help_text='Overall recommendation'),
        ),
    ]
