# Generated by Django 2.0 on 2018-02-01 22:30

from django.db import migrations, models
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20180201_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='decision',
        ),
        migrations.AddField(
            model_name='application',
            name='review_decision',
            field=models.BooleanField(default=True, help_text='Whether we intend to review this application'),
        ),
        migrations.AddField(
            model_name='application',
            name='interview1_decision',
            field=models.NullBooleanField(help_text='Whether we intend to interview this applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='interview2_decision',
            field=models.NullBooleanField(help_text='Whether we intend to give this applicant a second interview'),
        ),
        migrations.AddField(
            model_name='application',
            name='final_decision',
            field=review.models.EnumCharField([('accept', 'Accept'), ('reject', 'Reject'), ('waitlist', 'Waitlist')], blank=True),
        ),
    ]
