# Generated by Django 2.0 on 2018-02-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20180201_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview1_decision',
            field=models.NullBooleanField(help_text='Whether we intend to interview this applicant', verbose_name='Interview (Round 1)?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='interview2_decision',
            field=models.NullBooleanField(help_text='Whether we intend to give this applicant a second interview', verbose_name='Interview (Round 2)?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='review_decision',
            field=models.BooleanField(default=True, help_text='Whether we intend to review this application', verbose_name='Review?'),
        ),
    ]
