# Generated by Django 2.0 on 2018-02-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20180207_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='communication_rating',
            field=models.IntegerField(null=True, verbose_name='Communication Ability'),
        ),
        migrations.AlterField(
            model_name='review',
            name='data_handling_rating',
            field=models.IntegerField(null=True, verbose_name='Data Handling & Manipulation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='interest_in_good_rating',
            field=models.IntegerField(null=True, verbose_name='Interest in Social Good'),
        ),
        migrations.AlterField(
            model_name='review',
            name='machine_learning_rating',
            field=models.IntegerField(null=True, verbose_name='Stats & Machine Learning'),
        ),
        migrations.AlterField(
            model_name='review',
            name='programming_rating',
            field=models.IntegerField(null=True, verbose_name='Programming'),
        ),
        migrations.AlterField(
            model_name='review',
            name='teamwork_rating',
            field=models.IntegerField(null=True, verbose_name='Teamwork and Collaboration'),
        ),
    ]
