# Generated by Django 2.0 on 2018-02-15 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20180215_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAssignment',
            fields=[
                ('interview_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_assignments', to='review.Application')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_assignments', to=settings.AUTH_USER_MODEL)),
                ('interview_round', review.models.EnumIntegerField([('round_one', '1'), ('round_two', '2')])),  # FIXME
                ('assigned', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notified', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'interview_assignment',
                'ordering': ('-assigned',),
            },
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='interviewassignment',
            unique_together={('application', 'reviewer', 'interview_round')},
        ),
    ]
