# Generated by Django 2.0 on 2018-02-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_auto_20180215_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-created',)},
        ),
    ]
