# Generated by Django 2.0 on 2018-02-16 02:57

from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20180216_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReview',
            fields=[
                ('interview_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='review.InterviewAssignment')),
                ('programming_rating', models.IntegerField(null=True, verbose_name='Programming')),
                ('machine_learning_rating', models.IntegerField(null=True, verbose_name='Stats & Machine Learning')),
                ('data_handling_rating', models.IntegerField(null=True, verbose_name='Data Handling & Manipulation')),
                ('social_science', models.IntegerField(null=True, verbose_name='Social Science')),
                ('interest_in_good_rating', models.IntegerField(null=True, verbose_name='Interest in Social Good')),
                ('communication_rating', models.IntegerField(null=True, verbose_name='Communication Ability')),
                ('teamwork_rating', models.IntegerField(null=True, verbose_name='Teamwork and Collaboration')),
                ('overall_recommendation', review.models.EnumCharField([('accept', 'Accept'), ('reject', 'Reject'), ('only_if', 'Accept <em>only</em> if you need a certain type of fellow (explain below)')], help_text='Overall recommendation')),
                ('comments', models.TextField(blank=True, help_text='Any comments?')),
                ('submitted', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'interview_review',
                'ordering': ('-submitted',),
            },
        ),
    ]
