# Generated by Django 2.0 on 2018-02-17 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_interviewreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewreview',
            name='candidate_rank',
            field=models.TextField(blank=True, help_text="How does this candidate compare to others you've interviewed? Once you've completed all of your interviews, please rank this candidate within your interview pool."),
        ),
        migrations.AlterField(
            model_name='interviewreview',
            name='interview_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='interview_review', serialize=False, to='review.InterviewAssignment'),
        ),
    ]
