# Generated by Django 2.0 on 2018-02-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20180217_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='withdrawn',
            field=models.DateTimeField(null=True),
        ),
    ]
