# Generated by Django 2.1.5 on 2019-02-05 19:21

from django.db import migrations
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_application_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationreview',
            name='overall_recommendation',
            field=review.models.EnumCharField([('interview', 'Interview &ndash; definitely!'), ('maybe_interview', 'Interview &hellip; maybe'), ('only_if', 'Interview <em>only</em> if you need a certain type of fellow (explain below)'), ('reject', 'Reject')], help_text='Overall recommendation'),
        ),
    ]
