# Generated by Django 2.1.5 on 2019-02-07 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_auto_20190205_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewer',
            options={'ordering': ('email',)},
        ),

        migrations.CreateModel(
            name='ReviewerConcession',
            fields=[
                ('reviewer_concession_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_year', models.IntegerField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('is_interviewer', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviewer_concession',
                'ordering': ('-program_year', 'reviewer'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='reviewerconcession',
            unique_together={('program_year', 'reviewer')},
        ),
    ]
