# Generated by Django 2.1.5 on 2019-02-07 22:05

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_auto_20190207_2129'),
    ]

    operations = [
        CITextExtension(),

        migrations.AlterField(
            model_name='reviewer',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'A reviewer with that email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
