# Generated by Django 2.1.7 on 2019-02-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_auto_20190207_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewreview',
            name='question_code_communication',
            field=models.TextField(blank=True, help_text='When asked to explain and walk though the code, were they able to explain the code well?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_code_factoring',
            field=models.TextField(blank=True, help_text='Was the code modular? Did they write functions? Were the functions one-line functions, pages long, or somewhere in between?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_code_inputs',
            field=models.TextField(blank=True, help_text='What were the inputs to the program/functions?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_code_language',
            field=models.TextField(blank=True, help_text='Was the code written in Python?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_code_modularity',
            field=models.TextField(blank=True, help_text='Was the repository/code one big Jupyter notebook or one .py file? Or was it structured as several .py files and libraries/modules?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_code_outputs',
            field=models.TextField(blank=True, help_text='What were the outputs of the program/functions?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_code_parameterization',
            field=models.TextField(blank=True, help_text='Did the code have a lot of hard coded constants or was it designed to use parameters?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_code_structure',
            field=models.TextField(blank=True, help_text='Was it a script (series of statements) or structured as a program?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_data_analysis',
            field=models.TextField(blank=True, help_text='What analysis did they do – explain the methods used and alternatives considered.'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_data_cleaning',
            field=models.TextField(blank=True, help_text='How did they perform data cleaning?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_data_evaluation',
            field=models.TextField(blank=True, help_text='How did they evaluate the analysis – what metric, why, and what does the metric mean?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_data_goal',
            field=models.TextField(blank=True, help_text='What was the goal of the project?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_data_retrospective',
            field=models.TextField(blank=True, help_text='What would the impact be if this project were successful? What actions would be done differently?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_data_source',
            field=models.TextField(blank=True, help_text='What data was used and why was that data appropriate to use for that task?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_other_expectations',
            field=models.TextField(blank=True, help_text='What do they expect to gain or learn from DSSG?'),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='question_other_previous_projects',
            field=models.TextField(blank=True, help_text='What previous DSSG projects appealed to them?'),
        ),
    ]
