# Generated by Django 2.2.9 on 2020-02-14 19:41

from django.db import migrations
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0023_auto_20190306_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewreview',
            name='overall_recommendation',
            field=review.models.EnumCharField([('accept', 'Definitely accept'), ('probably_accept', 'Probably accept'), ('reject', 'Reject'), ('only_if', 'Accept <em>only</em> if you need a certain type of fellow (explain below)')], help_text='Overall recommendation'),
        ),
    ]
