# Generated by Django 2.2.25 on 2022-01-08 23:31

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0025_dedupe_applicant_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'An applicant with that email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
