# Generated by Django 2.2.25 on 2022-01-14 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0026_auto_20220108_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCompleteMessage',
            fields=[
                ('email_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_complete_message', to='review.Application')),
            ],
            options={
                'db_table': 'email_message_application_complete',
                'ordering': ('-sent',),
                'abstract': False,
            },
        ),
    ]
